//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniHulu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Episode
    {
        public int EpisodeID { get; set; }
        public Nullable<int> ShowID { get; set; }
        public Nullable<int> SeasonNumber { get; set; }
        public Nullable<int> EpisodeNumber { get; set; }
        public string Title { get; set; }
        public Nullable<int> Runtime { get; set; }
        public string Summary { get; set; }
    
        public virtual TVShow TVShow { get; set; }
    }
}
