//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniHulu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TVShow
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TVShow()
        {
            this.Episodes = new HashSet<Episode>();
        }
    
        public int ShowID { get; set; }
        public Nullable<int> NetworkID { get; set; }
        public string Title { get; set; }
        public string Genre { get; set; }
        public string Summary { get; set; }
        public string CoverImage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Episode> Episodes { get; set; }
        public virtual TVNetwork TVNetwork { get; set; }
    }
}
